### ISSUE TITLE
Responsive screen suggestion

### ISSUE THREAD

**Issue by zackha** [orhun/CoolModFiles#29]
This is a very nice project. I've been listening on nightride.fm for a very long time. Now I have a new alternative. It's not a big problem, but the interface is not responsive. This retro design looks very good on small screen browsers.

**Comment by orhun** [comment]
Hey, thanks for the nice words!

What part is exactly bugging your eyes about responsiveness? Since we don't support mobile devices (due to the limitation of OpenMPT), it shouldn't be a big problem but we would happily work on it if you can give us some details 🐻 cc @bufgix

**Comment by zackha** [comment]
I didn't know that the reason it didn't work on mobile was OpenMpt. An error occurs on the 14 inch screen as follows. When I checked your .css, you paid attention to the percentage of the dimensions. Errors such as the following seem to have occurred at points that were not paid attention to.

![image](https://user-images.githubusercontent.com/79358543/151719872-feb160c8-4735-4829-89a8-a4b2a727f19a.png)

![image](https://user-images.githubusercontent.com/79358543/151719900-6428fb6e-ac6f-470d-8fcb-f72a117d4b33.png)
