### ISSUE TITLE
Show random messages on page refresh

### ISSUE THREAD

**Issue by orhun** [orhun/CoolModFiles#39]
We might want to add another list of random messages for showing on page refresh.

Inspiration comes from #38 ✨

**Comment by orhun** [comment]
> Hello @orhun! I would like to work on this. Can you please assign it to me?

Great, thanks! 🐻 Let me know if you need any guidance.

> I can also make a small backend and database part, to get random messages right from the database.

We can put the quotes/messages in a const array for now but I'm curious about what's on your mind. What would be the easiest and most straightforward way of implementing such store?

**Comment by DreuXXX** [comment]
Well, since the frontend is done in React, what about to use simple Node.js express REST API with any kind of database(MongoDB or Postgres for example). But yeah, for start I can store it into const array and then we can discuss some upgrades.

**Comment by orhun** [comment]
Sounds good! Let's go step by step 👍🏼 We can discuss the database feature in a separate issue I think.

**Comment by orhun** [comment]
Implemented in #40
