### ISSUE TITLE
modules don't loop as the artist intended

### ISSUE THREAD

**Issue by runlow** [orhun/CoolModFiles#47]
**Expected**
The song loops the way the artist intended it to loop (usually so it continues seamlessly like an infinite song)

**Actual**
The song loops from the very beginning with the intro again

**Steps to reproduce**
1. open https://modarchive.org/index.php?request=view_player&query=180439
1. fast forward it near the end, notice how the song continues after it's over
1. open https://coolmodfiles.com/?trackId=180439
1. make sure "repeat" is on, fast forward near the end, notice what happens when it's over

**Extra**
I don't know if it's a bug or a feature. Personally I prefer the originally intended looping, even if it breaks immersion.

There's another issue of "sub-songs".
https://modarchive.org/index.php?request=view_player&query=38420
This is three songs in one. The following link only plays the first one.
https://coolmodfiles.com/?trackId=38420

Do you think maybe there's some clever way to still get to have sub-songs and the intended looping but without breaking the "typical playback" experience? Most songs don't use this so maybe it wouldn't be a big deal if some songs had an extra "song select ui"? I like the overall design by the way.

**Comment by WKFO** [comment]
Pressing the loop mode could toggle between 3 options: "loop off", "loop from start", "follow mod-defined loops". I just really hope it is not something that needs to be implemented on the OpenMPT side and its just a CoolModFiles issue (I've never looked at the code that reads/parses the files).

**Comment by runlow** [comment]
@WKFO There's another issue - that the listener may not even know that the song has "custom looping", this only applies to some select tracks

What if for now this could be only a semi-hidden keyboard shortcut, only announced in the help message, two key bindings:
 - a keyboard shortcut that activates "intended looping" and supersedes all normal looping and non-looping
 - a keyboard shortcut that simply to the next sub song (switches back to first on the last sub song)

**Comment by orhun** [comment]
The fix in #50 is now merged. I believe this will be somehow helpful.

For the other issues mentioned here, please create separate "feature request" issues. It is hard to track what else might be done here.

**Comment by runlow** [comment]
Thanks. It loops as intended now.

Sure, I can create separate issues for some of the things mentioned.
