### ISSUE TITLE
Unable to skip ahead in track

### ISSUE THREAD

**Issue by WKFO** [orhun/CoolModFiles#52]
I'm back with probably what's another edge-case issue.

Playing [track id 138328](https://coolmodfiles.com/?trackId=138328), you can not skip ahead further into the track. Attempting to do so ends the track and loads a new one - unless one has repeat turned on, in which case it will just not skip ahead and do a weird echo (double playing every note) for the duration of a single pattern before fixing itself. I don't know if this has something to do with libopenmpt handling .xm files, but I don't remember all .xm files doing this, just this specific track.

Here is the details in bullet list form, for further clarification:
- You can skip backwards. If the current playing time is 01:00, you can skip back to 00:30.
- You can not skip forwards. If the current playing time is 01:00, and you attempt to skip to 01:30, it fails.
- If you wait until the song plays to 02:00, and try to skip to 01:30, it works.
- Track id 138328 is the only instance of this occuring that I know of.
- Big player or compact player mode doesn't matter.

My browser is Mozilla Firefox, if that matters.

**Comment by WKFO** [comment]
Another occurrence is [track id 113527](https://coolmodfiles.com/?trackId=113527). This one isn't an .xm, it is a .mod file.

**Comment by orhun** [comment]
pinging @Cthulhu2 in case he wants to debug this :3

**Comment by Cthulhu2** [comment]
Upgrade OpenMPT? There is a couple changes in the [0.6.0](https://lib.openmpt.org/doc/changelog.html), may be it's related:

> * libopenmpt can now detect infinite pattern loops and treats them as the song end. This means that setting a repeat count other than -1 now always guarantees that playback will eventually end. The song loop counter is decremented each time it ends up at the start of the infinite loop, so the song does not restart from the beginning even if the repeat count is not 0.
> * [openmpt::module::set_position_seconds()](https://lib.openmpt.org/doc/classopenmpt_1_1module.html#a1c88bebd5371d04a272c6d876b84222c) accuracy has been improved for modules with pattern loops.
